name: Test Suite

on:
  pull_request:
    branches: [master]

jobs:
  linting:
    name: Linting Checks
    runs-on: ubuntu-latest
    env:
      ACCOUNT_PRIVATE_KEY: ${{ secrets.ACCOUNT_PRIVATE_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Linting
        run: npm run lint

  tests:
    name: Smart Contract Tests
    runs-on: ubuntu-latest
    env:
      ACCOUNT_PRIVATE_KEY: ${{ secrets.ACCOUNT_PRIVATE_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'node_modules'
          key: node_modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npx hardhat test
